/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import java.io.*;

import com.drew.lang.GeoLocation;
import com.drew.metadata.*;
import com.drew.metadata.jpeg.JpegDirectory;
import com.drew.metadata.exif.*;
import com.drew.metadata.file.*;
import com.drew.imaging.*;
import com.drew.imaging.jpeg.*;

public class App {
	public static void main(String[] args) {
		try {
			System.out.println("Using commons-imaging:");
			new MetadataExample().metadataExample(new File(args[0]));

			System.out.println("Using metadata-extractor:");
			Metadata metadata = ImageMetadataReader.readMetadata(new File(args[0]));
			for (Directory directory : metadata.getDirectories()) {
				for (Tag tag : directory.getTags()) {
					System.out.println(tag);
				}
			}

			System.out.println("Using metadata-extractor to extract some:");
			FileSystemDirectory file = metadata.getFirstDirectoryOfType(FileSystemDirectory.class);
			if (file != null) {
				System.out.println(String.format("<tr><td colspan='2'>%s: %s</td></tr>", "文件", file.getString(FileSystemDirectory.TAG_FILE_NAME)));
				System.out.println(String.format("<tr><td colspan='2'>%s: %s</td></tr>", "大小", file.getString(FileSystemDirectory.TAG_FILE_SIZE)));
			}
			JpegDirectory dir = metadata.getFirstDirectoryOfType(JpegDirectory.class);
			if (dir != null) {
				System.out.println(String.format("<tr><td colspan='2'>%s: %sx%s</td></tr>", "尺寸", dir.getString(JpegDirectory.TAG_IMAGE_WIDTH), dir.getString(JpegDirectory.TAG_IMAGE_HEIGHT)));
			}
			ExifIFD0Directory exif = metadata.getFirstDirectoryOfType(ExifIFD0Directory.class);
			if (exif != null) {
				System.out.println(String.format("<tr><td colspan='2'>%s: %s</td></tr>", "设备", exif.getString(ExifIFD0Directory.TAG_MODEL)));
				System.out.println(String.format("<tr><td colspan='2'>%s: %s</td></tr>", "制造商", exif.getString(ExifIFD0Directory.TAG_MAKE)));
				System.out.println(String.format("<tr><td colspan='2'>%s: %s</td></tr>", "时间", exif.getString(ExifIFD0Directory.TAG_DATETIME)));
			}
			GpsDirectory gps = metadata.getFirstDirectoryOfType(GpsDirectory.class);
			if (gps != null) {
				GeoLocation loc = gps.getGeoLocation();
				System.out.println(String.format("<tr><td colspan='2'>%s: 经度%s, 纬度%s</td></tr>", "位置", GeoLocation.decimalToDegreesMinutesSecondsString(loc.getLongitude()), GeoLocation.decimalToDegreesMinutesSecondsString(loc.getLatitude())));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
